version: "3.8"

services:
  nginx:
    build: ./nginx/
    image: nginx:latest
    volumes:
      - /static:/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    restart: always
  db:
    image: postgres:12.8-alpine
    volumes:
      - /postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5832:5432"
    restart: always
  web:
    build: .
    command: >
      sh -c "cd bank_account_app && ls && python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn bank_account_app.wsgi --bind 0.0.0.0:8000
            "
    volumes:
      - /bank_account_app/:/usr/src/app/
      - /static:/static
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_volume:
  web_volume: