# Generated by Django 4.0.3 on 2022-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ManyToManyField(blank=True, to='bank_account.bankaccount', verbose_name='Bank Account'),
        ),
    ]
