# Generated by Django 4.0.3 on 2022-03-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_bankaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_bank_account', to='bank_account.bankaccount', verbose_name='Recipient bank account'),
        ),
    ]
