# Generated by Django 4.0.3 on 2022-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_transaction_recipient_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
